# coding: utf-8

"""
    Competence Repository

    The API description of the Competence Repository.  # noqa: E501

    OpenAPI spec version: 0.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.learning_object_modification_dto import LearningObjectModificationDto  # noqa: E501
from swagger_client.rest import ApiException


class TestLearningObjectModificationDto(unittest.TestCase):
    """LearningObjectModificationDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLearningObjectModificationDto(self):
        """Test LearningObjectModificationDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.learning_object_modification_dto.LearningObjectModificationDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
