# coding: utf-8

"""
    Competence Repository

    The API description of the Competence Repository.  # noqa: E501

    OpenAPI spec version: 0.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.lo_goal_dto import LoGoalDto  # noqa: E501
from swagger_client.rest import ApiException


class TestLoGoalDto(unittest.TestCase):
    """LoGoalDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoGoalDto(self):
        """Test LoGoalDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.lo_goal_dto.LoGoalDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
