# coding: utf-8

"""
    Competence Repository

    The API description of the Competence Repository.  # noqa: E501

    OpenAPI spec version: 0.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ueber_competence_modification_dto import UeberCompetenceModificationDto  # noqa: E501
from swagger_client.rest import ApiException


class TestUeberCompetenceModificationDto(unittest.TestCase):
    """UeberCompetenceModificationDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUeberCompetenceModificationDto(self):
        """Test UeberCompetenceModificationDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ueber_competence_modification_dto.UeberCompetenceModificationDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
