# coding: utf-8

"""
    Competence Repository

    The API description of the Competence Repository.  # noqa: E501

    OpenAPI spec version: 0.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LearningObjectDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'lo_repository_id': 'str',
        'name': 'str',
        'description': 'str',
        'required_competencies': 'list[str]',
        'required_ueber_competencies': 'list[str]',
        'offered_competencies': 'list[str]',
        'offered_ueber_competencies': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'lo_repository_id': 'loRepositoryId',
        'name': 'name',
        'description': 'description',
        'required_competencies': 'requiredCompetencies',
        'required_ueber_competencies': 'requiredUeberCompetencies',
        'offered_competencies': 'offeredCompetencies',
        'offered_ueber_competencies': 'offeredUeberCompetencies'
    }

    def __init__(self, id=None, lo_repository_id=None, name=None, description=None, required_competencies=None, required_ueber_competencies=None, offered_competencies=None, offered_ueber_competencies=None):  # noqa: E501
        """LearningObjectDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._lo_repository_id = None
        self._name = None
        self._description = None
        self._required_competencies = None
        self._required_ueber_competencies = None
        self._offered_competencies = None
        self._offered_ueber_competencies = None
        self.discriminator = None
        self.id = id
        self.lo_repository_id = lo_repository_id
        self.name = name
        if description is not None:
            self.description = description
        self.required_competencies = required_competencies
        self.required_ueber_competencies = required_ueber_competencies
        self.offered_competencies = offered_competencies
        self.offered_ueber_competencies = offered_ueber_competencies

    @property
    def id(self):
        """Gets the id of this LearningObjectDto.  # noqa: E501


        :return: The id of this LearningObjectDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LearningObjectDto.


        :param id: The id of this LearningObjectDto.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def lo_repository_id(self):
        """Gets the lo_repository_id of this LearningObjectDto.  # noqa: E501


        :return: The lo_repository_id of this LearningObjectDto.  # noqa: E501
        :rtype: str
        """
        return self._lo_repository_id

    @lo_repository_id.setter
    def lo_repository_id(self, lo_repository_id):
        """Sets the lo_repository_id of this LearningObjectDto.


        :param lo_repository_id: The lo_repository_id of this LearningObjectDto.  # noqa: E501
        :type: str
        """
        if lo_repository_id is None:
            raise ValueError("Invalid value for `lo_repository_id`, must not be `None`")  # noqa: E501

        self._lo_repository_id = lo_repository_id

    @property
    def name(self):
        """Gets the name of this LearningObjectDto.  # noqa: E501


        :return: The name of this LearningObjectDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LearningObjectDto.


        :param name: The name of this LearningObjectDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this LearningObjectDto.  # noqa: E501


        :return: The description of this LearningObjectDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this LearningObjectDto.


        :param description: The description of this LearningObjectDto.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def required_competencies(self):
        """Gets the required_competencies of this LearningObjectDto.  # noqa: E501


        :return: The required_competencies of this LearningObjectDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._required_competencies

    @required_competencies.setter
    def required_competencies(self, required_competencies):
        """Sets the required_competencies of this LearningObjectDto.


        :param required_competencies: The required_competencies of this LearningObjectDto.  # noqa: E501
        :type: list[str]
        """
        if required_competencies is None:
            raise ValueError("Invalid value for `required_competencies`, must not be `None`")  # noqa: E501

        self._required_competencies = required_competencies

    @property
    def required_ueber_competencies(self):
        """Gets the required_ueber_competencies of this LearningObjectDto.  # noqa: E501


        :return: The required_ueber_competencies of this LearningObjectDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._required_ueber_competencies

    @required_ueber_competencies.setter
    def required_ueber_competencies(self, required_ueber_competencies):
        """Sets the required_ueber_competencies of this LearningObjectDto.


        :param required_ueber_competencies: The required_ueber_competencies of this LearningObjectDto.  # noqa: E501
        :type: list[str]
        """
        if required_ueber_competencies is None:
            raise ValueError("Invalid value for `required_ueber_competencies`, must not be `None`")  # noqa: E501

        self._required_ueber_competencies = required_ueber_competencies

    @property
    def offered_competencies(self):
        """Gets the offered_competencies of this LearningObjectDto.  # noqa: E501


        :return: The offered_competencies of this LearningObjectDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._offered_competencies

    @offered_competencies.setter
    def offered_competencies(self, offered_competencies):
        """Sets the offered_competencies of this LearningObjectDto.


        :param offered_competencies: The offered_competencies of this LearningObjectDto.  # noqa: E501
        :type: list[str]
        """
        if offered_competencies is None:
            raise ValueError("Invalid value for `offered_competencies`, must not be `None`")  # noqa: E501

        self._offered_competencies = offered_competencies

    @property
    def offered_ueber_competencies(self):
        """Gets the offered_ueber_competencies of this LearningObjectDto.  # noqa: E501


        :return: The offered_ueber_competencies of this LearningObjectDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._offered_ueber_competencies

    @offered_ueber_competencies.setter
    def offered_ueber_competencies(self, offered_ueber_competencies):
        """Sets the offered_ueber_competencies of this LearningObjectDto.


        :param offered_ueber_competencies: The offered_ueber_competencies of this LearningObjectDto.  # noqa: E501
        :type: list[str]
        """
        if offered_ueber_competencies is None:
            raise ValueError("Invalid value for `offered_ueber_competencies`, must not be `None`")  # noqa: E501

        self._offered_ueber_competencies = offered_ueber_competencies

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LearningObjectDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LearningObjectDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
