# coding: utf-8

"""
    Competence Repository

    The API description of the Competence Repository.  # noqa: E501

    OpenAPI spec version: 0.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UberCompetenceResolveRequestDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uber_competencies': 'list[str]'
    }

    attribute_map = {
        'uber_competencies': 'uberCompetencies'
    }

    def __init__(self, uber_competencies=None):  # noqa: E501
        """UberCompetenceResolveRequestDto - a model defined in Swagger"""  # noqa: E501
        self._uber_competencies = None
        self.discriminator = None
        self.uber_competencies = uber_competencies

    @property
    def uber_competencies(self):
        """Gets the uber_competencies of this UberCompetenceResolveRequestDto.  # noqa: E501


        :return: The uber_competencies of this UberCompetenceResolveRequestDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._uber_competencies

    @uber_competencies.setter
    def uber_competencies(self, uber_competencies):
        """Sets the uber_competencies of this UberCompetenceResolveRequestDto.


        :param uber_competencies: The uber_competencies of this UberCompetenceResolveRequestDto.  # noqa: E501
        :type: list[str]
        """
        if uber_competencies is None:
            raise ValueError("Invalid value for `uber_competencies`, must not be `None`")  # noqa: E501

        self._uber_competencies = uber_competencies

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UberCompetenceResolveRequestDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UberCompetenceResolveRequestDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
