# coding: utf-8

"""
    Competence Repository

    The API description of the Competence Repository.  # noqa: E501

    OpenAPI spec version: 0.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompetenceCreationDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'skill': 'str',
        'level': 'float',
        'description': 'str'
    }

    attribute_map = {
        'skill': 'skill',
        'level': 'level',
        'description': 'description'
    }

    def __init__(self, skill=None, level=None, description=None):  # noqa: E501
        """CompetenceCreationDto - a model defined in Swagger"""  # noqa: E501
        self._skill = None
        self._level = None
        self._description = None
        self.discriminator = None
        self.skill = skill
        self.level = level
        if description is not None:
            self.description = description

    @property
    def skill(self):
        """Gets the skill of this CompetenceCreationDto.  # noqa: E501


        :return: The skill of this CompetenceCreationDto.  # noqa: E501
        :rtype: str
        """
        return self._skill

    @skill.setter
    def skill(self, skill):
        """Sets the skill of this CompetenceCreationDto.


        :param skill: The skill of this CompetenceCreationDto.  # noqa: E501
        :type: str
        """
        if skill is None:
            raise ValueError("Invalid value for `skill`, must not be `None`")  # noqa: E501

        self._skill = skill

    @property
    def level(self):
        """Gets the level of this CompetenceCreationDto.  # noqa: E501


        :return: The level of this CompetenceCreationDto.  # noqa: E501
        :rtype: float
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this CompetenceCreationDto.


        :param level: The level of this CompetenceCreationDto.  # noqa: E501
        :type: float
        """
        if level is None:
            raise ValueError("Invalid value for `level`, must not be `None`")  # noqa: E501

        self._level = level

    @property
    def description(self):
        """Gets the description of this CompetenceCreationDto.  # noqa: E501


        :return: The description of this CompetenceCreationDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CompetenceCreationDto.


        :param description: The description of this CompetenceCreationDto.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompetenceCreationDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompetenceCreationDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
