# coding: utf-8

"""
    Competence Repository

    The API description of the Competence Repository.  # noqa: E501

    OpenAPI spec version: 0.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LoGoalCreationDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'competencies': 'list[str]',
        'uber_competencies': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'competencies': 'competencies',
        'uber_competencies': 'uberCompetencies'
    }

    def __init__(self, name=None, description=None, competencies=None, uber_competencies=None):  # noqa: E501
        """LoGoalCreationDto - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._description = None
        self._competencies = None
        self._uber_competencies = None
        self.discriminator = None
        self.name = name
        if description is not None:
            self.description = description
        self.competencies = competencies
        self.uber_competencies = uber_competencies

    @property
    def name(self):
        """Gets the name of this LoGoalCreationDto.  # noqa: E501


        :return: The name of this LoGoalCreationDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LoGoalCreationDto.


        :param name: The name of this LoGoalCreationDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this LoGoalCreationDto.  # noqa: E501


        :return: The description of this LoGoalCreationDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this LoGoalCreationDto.


        :param description: The description of this LoGoalCreationDto.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def competencies(self):
        """Gets the competencies of this LoGoalCreationDto.  # noqa: E501


        :return: The competencies of this LoGoalCreationDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._competencies

    @competencies.setter
    def competencies(self, competencies):
        """Sets the competencies of this LoGoalCreationDto.


        :param competencies: The competencies of this LoGoalCreationDto.  # noqa: E501
        :type: list[str]
        """
        if competencies is None:
            raise ValueError("Invalid value for `competencies`, must not be `None`")  # noqa: E501

        self._competencies = competencies

    @property
    def uber_competencies(self):
        """Gets the uber_competencies of this LoGoalCreationDto.  # noqa: E501


        :return: The uber_competencies of this LoGoalCreationDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._uber_competencies

    @uber_competencies.setter
    def uber_competencies(self, uber_competencies):
        """Sets the uber_competencies of this LoGoalCreationDto.


        :param uber_competencies: The uber_competencies of this LoGoalCreationDto.  # noqa: E501
        :type: list[str]
        """
        if uber_competencies is None:
            raise ValueError("Invalid value for `uber_competencies`, must not be `None`")  # noqa: E501

        self._uber_competencies = uber_competencies

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LoGoalCreationDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoGoalCreationDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
