# coding: utf-8

"""
    Competence Repository

    The API description of the Competence Repository.  # noqa: E501

    OpenAPI spec version: 0.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LoRepositoryDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'owner': 'str',
        'description': 'str',
        'learning_objects': 'list[LearningObjectDto]',
        'learning_objects_groups': 'list[LearningObjectGroupDto]',
        'goals': 'list[LoGoalDto]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'owner': 'owner',
        'description': 'description',
        'learning_objects': 'learningObjects',
        'learning_objects_groups': 'learningObjectsGroups',
        'goals': 'goals'
    }

    def __init__(self, id=None, name=None, owner=None, description=None, learning_objects=None, learning_objects_groups=None, goals=None):  # noqa: E501
        """LoRepositoryDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._owner = None
        self._description = None
        self._learning_objects = None
        self._learning_objects_groups = None
        self._goals = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.owner = owner
        if description is not None:
            self.description = description
        self.learning_objects = learning_objects
        self.learning_objects_groups = learning_objects_groups
        self.goals = goals

    @property
    def id(self):
        """Gets the id of this LoRepositoryDto.  # noqa: E501


        :return: The id of this LoRepositoryDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LoRepositoryDto.


        :param id: The id of this LoRepositoryDto.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this LoRepositoryDto.  # noqa: E501


        :return: The name of this LoRepositoryDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LoRepositoryDto.


        :param name: The name of this LoRepositoryDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def owner(self):
        """Gets the owner of this LoRepositoryDto.  # noqa: E501


        :return: The owner of this LoRepositoryDto.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this LoRepositoryDto.


        :param owner: The owner of this LoRepositoryDto.  # noqa: E501
        :type: str
        """
        if owner is None:
            raise ValueError("Invalid value for `owner`, must not be `None`")  # noqa: E501

        self._owner = owner

    @property
    def description(self):
        """Gets the description of this LoRepositoryDto.  # noqa: E501


        :return: The description of this LoRepositoryDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this LoRepositoryDto.


        :param description: The description of this LoRepositoryDto.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def learning_objects(self):
        """Gets the learning_objects of this LoRepositoryDto.  # noqa: E501


        :return: The learning_objects of this LoRepositoryDto.  # noqa: E501
        :rtype: list[LearningObjectDto]
        """
        return self._learning_objects

    @learning_objects.setter
    def learning_objects(self, learning_objects):
        """Sets the learning_objects of this LoRepositoryDto.


        :param learning_objects: The learning_objects of this LoRepositoryDto.  # noqa: E501
        :type: list[LearningObjectDto]
        """
        if learning_objects is None:
            raise ValueError("Invalid value for `learning_objects`, must not be `None`")  # noqa: E501

        self._learning_objects = learning_objects

    @property
    def learning_objects_groups(self):
        """Gets the learning_objects_groups of this LoRepositoryDto.  # noqa: E501


        :return: The learning_objects_groups of this LoRepositoryDto.  # noqa: E501
        :rtype: list[LearningObjectGroupDto]
        """
        return self._learning_objects_groups

    @learning_objects_groups.setter
    def learning_objects_groups(self, learning_objects_groups):
        """Sets the learning_objects_groups of this LoRepositoryDto.


        :param learning_objects_groups: The learning_objects_groups of this LoRepositoryDto.  # noqa: E501
        :type: list[LearningObjectGroupDto]
        """
        if learning_objects_groups is None:
            raise ValueError("Invalid value for `learning_objects_groups`, must not be `None`")  # noqa: E501

        self._learning_objects_groups = learning_objects_groups

    @property
    def goals(self):
        """Gets the goals of this LoRepositoryDto.  # noqa: E501


        :return: The goals of this LoRepositoryDto.  # noqa: E501
        :rtype: list[LoGoalDto]
        """
        return self._goals

    @goals.setter
    def goals(self, goals):
        """Sets the goals of this LoRepositoryDto.


        :param goals: The goals of this LoRepositoryDto.  # noqa: E501
        :type: list[LoGoalDto]
        """
        if goals is None:
            raise ValueError("Invalid value for `goals`, must not be `None`")  # noqa: E501

        self._goals = goals

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LoRepositoryDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoRepositoryDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
