# coding: utf-8

"""
    Competence Repository

    The API description of the Competence Repository.  # noqa: E501

    OpenAPI spec version: 0.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.competencies_api import CompetenciesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCompetenciesApi(unittest.TestCase):
    """CompetenciesApi unit test stubs"""

    def setUp(self):
        self.api = CompetenciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_repository_mgmt_controller_add_competence(self):
        """Test case for repository_mgmt_controller_add_competence

        """
        pass

    def test_repository_mgmt_controller_add_ueber_competence(self):
        """Test case for repository_mgmt_controller_add_ueber_competence

        """
        pass

    def test_repository_mgmt_controller_create_repository(self):
        """Test case for repository_mgmt_controller_create_repository

        """
        pass

    def test_repository_mgmt_controller_list_repositories(self):
        """Test case for repository_mgmt_controller_list_repositories

        """
        pass

    def test_repository_mgmt_controller_load_repository(self):
        """Test case for repository_mgmt_controller_load_repository

        """
        pass

    def test_repository_mgmt_controller_load_resolved_repository(self):
        """Test case for repository_mgmt_controller_load_resolved_repository

        """
        pass

    def test_repository_mgmt_controller_modify(self):
        """Test case for repository_mgmt_controller_modify

        """
        pass

    def test_repository_mgmt_controller_search_for_repositories(self):
        """Test case for repository_mgmt_controller_search_for_repositories

        """
        pass


if __name__ == '__main__':
    unittest.main()
