# coding: utf-8

"""
    Competence Repository

    The API description of the Competence Repository.  # noqa: E501

    OpenAPI spec version: 0.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.unresolved_repository_dto import UnresolvedRepositoryDto  # noqa: E501
from swagger_client.rest import ApiException


class TestUnresolvedRepositoryDto(unittest.TestCase):
    """UnresolvedRepositoryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnresolvedRepositoryDto(self):
        """Test UnresolvedRepositoryDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.unresolved_repository_dto.UnresolvedRepositoryDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
