# coding: utf-8

"""
    Competence Repository

    The API description of the Competence Repository.  # noqa: E501

    OpenAPI spec version: 0.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.learning_objects_api import LearningObjectsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLearningObjectsApi(unittest.TestCase):
    """LearningObjectsApi unit test stubs"""

    def setUp(self):
        self.api = LearningObjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_lo_repository_controller_add_goal(self):
        """Test case for lo_repository_controller_add_goal

        """
        pass

    def test_lo_repository_controller_create_learning_object(self):
        """Test case for lo_repository_controller_create_learning_object

        """
        pass

    def test_lo_repository_controller_create_repository(self):
        """Test case for lo_repository_controller_create_repository

        """
        pass

    def test_lo_repository_controller_list_repositories(self):
        """Test case for lo_repository_controller_list_repositories

        """
        pass

    def test_lo_repository_controller_load_learning_object(self):
        """Test case for lo_repository_controller_load_learning_object

        """
        pass

    def test_lo_repository_controller_load_repository(self):
        """Test case for lo_repository_controller_load_repository

        """
        pass

    def test_lo_repository_controller_modify_learning_object(self):
        """Test case for lo_repository_controller_modify_learning_object

        """
        pass

    def test_lo_repository_controller_modify_repository(self):
        """Test case for lo_repository_controller_modify_repository

        """
        pass

    def test_lo_repository_controller_show_goal(self):
        """Test case for lo_repository_controller_show_goal

        """
        pass

    def test_lo_repository_controller_show_goals(self):
        """Test case for lo_repository_controller_show_goals

        """
        pass


if __name__ == '__main__':
    unittest.main()
