# coding: utf-8

"""
    Competence Repository

    The API description of the Competence Repository.  # noqa: E501

    OpenAPI spec version: 0.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.lo_repository_modify_dto import LoRepositoryModifyDto  # noqa: E501
from swagger_client.rest import ApiException


class TestLoRepositoryModifyDto(unittest.TestCase):
    """LoRepositoryModifyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoRepositoryModifyDto(self):
        """Test LoRepositoryModifyDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.lo_repository_modify_dto.LoRepositoryModifyDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
